# Generated by Django 3.2.8 on 2021-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Tag (e.g. Community', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Activity Name', max_length=200)),
                ('description', models.TextField(help_text='Activity Description')),
                ('address', models.CharField(help_text='Activity Address', max_length=200)),
                ('datetime', models.DateTimeField()),
                ('tags', models.ManyToManyField(help_text='Select Tags', to='radius.ActivityTags')),
            ],
        ),
    ]
