# Generated by Django 3.2.8 on 2021-11-20 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(help_text='Activity Name', max_length=200)),
                ('description', models.TextField(help_text='Activity Description')),
                ('address', models.CharField(help_text='Activity Address', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Activity Key', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 20, 22, 42, 43, 154920))),
                ('longitude', models.FloatField(default=151.742)),
                ('latitude', models.FloatField(default=-33.871846)),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Tag (e.g. Community', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User Bio')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('postcode', models.IntegerField(default=2000)),
                ('radius', models.IntegerField(default=1)),
                ('avatar', models.IntegerField(choices=[(1, 'avat1.png'), (2, 'avat2.png'), (3, 'avat3.png'), (4, 'avat4.png'), (5, 'avat5.png'), (6, 'avat6.png'), (7, 'avat7.png')], default=1)),
                ('favourites', models.ManyToManyField(blank=True, related_name='user_favourites', to='radius.Activity')),
                ('history', models.ManyToManyField(blank=True, related_name='user_history', to='radius.Activity')),
                ('interests', models.ManyToManyField(to='radius.ActivityTags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Instance ID', primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='radius.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(help_text='Select Tags', to='radius.ActivityTags'),
        ),
    ]
