# Generated by Django 3.2.8 on 2021-11-02 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_alter_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Activity Key', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Instance ID', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='radius.activity')),
            ],
        ),
    ]
