# Generated by Django 3.2.8 on 2021-11-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0004_remove_activityinstance_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 22, 26, 12, 563907)),
        ),
    ]
