# Generated by Django 3.2.8 on 2021-11-06 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0005_activity_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(default=-33.871846),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(default=151.742),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 8, 46, 41, 64465)),
        ),
    ]
