# Generated by Django 3.2.8 on 2021-11-09 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radius', '0008_alter_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 21, 59, 7, 895586)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User Bio')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('avatar', models.IntegerField(choices=[(1, 'avat1.png'), (2, 'avat2.png'), (3, 'avat3.png'), (4, 'avat4.png'), (5, 'avat5.png'), (6, 'avat6.png'), (7, 'avat7.png')], default=1)),
                ('interests', models.ManyToManyField(to='radius.ActivityTags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
