# Generated by Django 3.2.8 on 2021-11-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0007_alter_activity_datetime'),
        ('radius', '0009_auto_20211109_2159'),
    ]

    operations = [
    ]
