# Generated by Django 3.2 on 2021-11-11 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0010_merge_20211110_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 5, 13, 29, 71136)),
        ),
    ]
