# Generated by Django 3.2.8 on 2021-11-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0014_alter_activity_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='radius',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 8, 23, 15, 342227)),
        ),
    ]
