# Generated by Django 3.2.8 on 2021-11-14 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0015_auto_20211113_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='user_favourites', to='radius.Activity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='user_history', to='radius.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 11, 0, 49, 703443)),
        ),
    ]
